### ISSUE TITLE
grsec patch outdated..

### ISSUE THREAD

**Issue by ingobecker** [nning/linux-grsec#4]
returns 404, please update ;)

**Comment by nning** [comment]
At least since yesterday, http://grsecurity.net/ responds really, really slow. I cannot determine if a newer patchset is available.

You can use [`update.rb`](https://github.com/nning/linux-grsec/blob/master/update.rb) locally if you are able to reach grsecurity.net or do not want to wait for the `PKGBUILD` to be updated here.

Closing this issue, for now; I will update as soon as my feed reader is able to reach grsecurity.net, again.

**Comment by nning** [comment]
Oh, I appearently forgot to push the changes for patch `201601051958`; they're online now.
